### PR TITLE
add metric type to duration

### PR DESCRIPTION
**Pull request by azylman**
So it gets picked up by our logging infrastructure

### CODE REVIEW

**Comment by azylman** [comment]
cc: @mohit I think I did this right?

**Comment by mohit** [comment]
Yes. But job_data is going to make the metric names very strange. You might have to setup a custom marcher if you want job_data to be in the same line as the duration. Or maybe influxdb will deal with it fine. 

We can test this on staging if you'd like

**Comment by kvigen** [comment]
very exciting!

**Comment by schimmy** [comment]
LGTM!

**Pull request merged**
