### PR TITLE
add a heartbeat log per retry of a job

### PR DESCRIPTION
**Pull request by natebrennand**
This adds a once per minute heartbeat log to be outputted for each retry
of a job.

-------

test strategy:

sleep.sh:
```sh
sleep 30
```

with `tickUnit := time.Second`...
```sh
go run cmd/gearcmd/*.go -cmd /home/vagrant/go/src/github.com/Clever/gearcmd/sleep.sh -name ticker-test -port 4730 -host <gearmand-server>
{"job":"ticker-test","level":"info","source":"gearcmd","title":"listening"}
{"function":"ticker-test","job_data":"{\"foo\":\"bar\"}","job_id":"214","level":"info","source":"gearcmd","title":"START"}
{"function":"ticker-test","job_id":"214","level":"info","source":"gearcmd","title":"heartbeat","try_number":0,"type":"gauge","unit":"1s","value":1}
{"function":"ticker-test","job_id":"214","level":"info","source":"gearcmd","title":"heartbeat","try_number":0,"type":"gauge","unit":"1s","value":2}
{"function":"ticker-test","job_id":"214","level":"info","source":"gearcmd","title":"heartbeat","try_number":0,"type":"gauge","unit":"1s","value":3}
{"function":"ticker-test","job_id":"214","level":"info","source":"gearcmd","title":"heartbeat","try_number":0,"type":"gauge","unit":"1s","value":4}
{"function":"ticker-test","job_id":"214","level":"info","source":"gearcmd","title":"heartbeat","try_number":0,"type":"gauge","unit":"1s","value":5}
{"function":"ticker-test","job_id":"214","level":"info","source":"gearcmd","title":"heartbeat","try_number":0,"type":"gauge","unit":"1s","value":6}
{"function":"ticker-test","job_id":"214","level":"info","source":"gearcmd","title":"heartbeat","try_number":0,"type":"gauge","unit":"1s","value":7}
{"function":"ticker-test","job_id":"214","level":"info","source":"gearcmd","title":"heartbeat","try_number":0,"type":"gauge","unit":"1s","value":8}
{"function":"ticker-test","job_id":"214","level":"info","source":"gearcmd","title":"heartbeat","try_number":0,"type":"gauge","unit":"1s","value":9}
{"function":"ticker-test","job_id":"214","level":"info","source":"gearcmd","title":"heartbeat","try_number":0,"type":"gauge","unit":"1s","value":10}
```

### CODE REVIEW

**Comment by evaninja** [comment]
LGTM

**Comment by agclever** [comment]
out of curiosity, why did we add the heartbeat logs?

**Comment by natebrennand** [comment]
@agclever: mainly for simpler alerting purposes. Check the ticket in the branch name for more context.

**Comment by agclever** [comment]
Thanks. The ticket was exactly the context I wanted :)

**Comment by johnhuangclever** [comment]
💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥

**Pull request merged**
