### PR TITLE
properly protect sigtermHandler in baseworker.Worker

### PR DESCRIPTION
**Pull request by natebrennand**
This fixes a graceful shutdown but that caused a deadlock.
Uses baseworker mutex instead of gearman-go/worker mutex to lock around sigtermhandler

### CODE REVIEW

**Comment by natebrennand** [comment]
This is the fix to the fix of the race condition
https://github.com/Clever/gearcmd/pull/39

CC @rgarcia

**Comment by jiancheung** [comment]
assuming this was verified to work, LGTM!

**Comment by natebrennand** [comment]
Verified with:
```
make clean && make build && docker build -t echo-test . && docker run echo-test
```

Dockerfile:
```dockerfile
FROM debian:jessie
COPY build/gearcmd-v0.6.0-linux-amd64/gearcmd /usr/local/bin

ENV SERVICE_GEARMAND_TCP_PROTO=tcp
ENV SERVICE_GEARMAND_TCP_HOST=hostname
ENV SERVICE_GEARMAND_TCP_PORT=4730

ADD wait.sh /usr/bin/wait.sh
CMD ["gearcmd", "--name=test", "--cmd=/usr/bin/wait.sh"]
```

I then sent a SIGTERM via `docker stop`, it properly stopped immediate since it was not handling a job at that time.

**Comment by mohit** [comment]
is there a way we could add that test to this repo. We would not be able to run it on drone, but maybe helpful as a `make sigtest`

**Comment by natebrennand** [comment]
@mohit: It definitely is possible, but would probably have to be in code (and not bash/make) due to the asynchronous and timing aspects...
I think it would be good to do, but I don't know when I have time to do it.

**Comment by mohit** [comment]
Are we not fixing this?

**Comment by natebrennand** [comment]
merged manually: https://github.com/Clever/gearcmd/commit/a775aaed5530684dc20d14239376e3f3b01617eb

**Pull request closed without merging**
